# Generated by Django 2.2.3 on 2019-09-09 17:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('latittude', models.DecimalField(blank=True, decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('state', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BillBoardBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('recommendation', models.CharField(max_length=100)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.BillBoard')),
            ],
        ),
        migrations.CreateModel(
            name='BoardSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmonitor.MediaAgency')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmonitor.Client')),
            ],
        ),
        migrations.AddField(
            model_name='mediaagency',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.Town'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('fileContent', models.FileField(upload_to='Files')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.BillBoard')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('avInShops', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('boardBrand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bmonitor.BillBoardBrand')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.Town'),
        ),
        migrations.CreateModel(
            name='BrandAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 20, 29, 9, 907289))),
                ('contract', models.CharField(default='ACTIVE', max_length=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.MediaAgency')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.Client'),
        ),
        migrations.AddField(
            model_name='billboardbrand',
            name='brandAgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonitor.BrandAgency'),
        ),
    ]
