# Generated by Django 2.2.3 on 2019-09-13 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmonitor', '0003_auto_20190909_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billboard',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 397599)),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 397599)),
        ),
        migrations.AlterField(
            model_name='billboardbrand',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 398598)),
        ),
        migrations.AlterField(
            model_name='billboardbrand',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 398598)),
        ),
        migrations.AlterField(
            model_name='boardsupplier',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 17, 44, 1, 402595)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 395602)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 395602)),
        ),
        migrations.AlterField(
            model_name='brandagency',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 396600)),
        ),
        migrations.AlterField(
            model_name='brandagency',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 396600)),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 394601)),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 394601)),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 400597)),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 400597)),
        ),
        migrations.AlterField(
            model_name='image',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 399597)),
        ),
        migrations.AlterField(
            model_name='mediaagency',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 393601)),
        ),
        migrations.AlterField(
            model_name='mediaagency',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 393601)),
        ),
        migrations.AlterField(
            model_name='town',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 393601)),
        ),
        migrations.AlterField(
            model_name='users',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 401596)),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 17, 44, 1, 401596)),
        ),
    ]
