# Generated by Django 2.2.3 on 2019-09-13 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmonitor', '0005_auto_20190913_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 330304)),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 330304)),
        ),
        migrations.AlterField(
            model_name='billboardbrand',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 331303)),
        ),
        migrations.AlterField(
            model_name='billboardbrand',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 331303)),
        ),
        migrations.AlterField(
            model_name='boardsupplier',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 18, 37, 41, 334302)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 329305)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 329305)),
        ),
        migrations.AlterField(
            model_name='brandagency',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 330304)),
        ),
        migrations.AlterField(
            model_name='brandagency',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 330304)),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 329305)),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 329305)),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 333303)),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 333303)),
        ),
        migrations.AlterField(
            model_name='image',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 332303)),
        ),
        migrations.AlterField(
            model_name='mediaagency',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 328305)),
        ),
        migrations.AlterField(
            model_name='mediaagency',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 328305)),
        ),
        migrations.AlterField(
            model_name='town',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 327306)),
        ),
        migrations.AlterField(
            model_name='users',
            name='agency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmonitor.MediaAgency'),
        ),
        migrations.AlterField(
            model_name='users',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmonitor.Client'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 334302)),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 18, 37, 41, 334302)),
        ),
    ]
